# This is a basic workflow to help you get started with Actions

name: Jmeter for performance testing

# Controls when the workflow will run
on:
  workflow_call:
    secrets:
      SOME_SECRET:
        required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
     
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@3.0
        with:
          # jmeter test plan to execute
          test-plan-path: './performancetest/performance.jmx'
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
           name: jmeter-results
           path: result.jtl    
        

    
