name: CI-CD

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:

  performance-testing:
    uses: devopslecturer/awmsc2022/.github/workflows/Jmeter.yml@Flask_Initial_Setup

 

