name: Main Job

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:

  performance-testing:
    uses: Anup-Jacob/Room-Reservation/.github/workflows/Jmeter.yml@Development

 

